sudo: required
services:
  - docker

before_install:
  - docker build -t kt/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true kt/docker-react npm run test

deploy:
  provider: heroku
  strategy: git
  app:
    master: kt-test-deploy
  on:
    branch: master